---
# Package configuration for Ojay build process
#
source_dir: source
build_dir: build
packages:
  js-class:
    encode_private_vars: false
    copyright: source/external/COPYRIGHT
    source_dir: external
    files:
      - class
      - method_chain
      - observable
      - state
  core:
    encode_private_vars: true
    include_version: true
    copyright: COPYRIGHT
    source_dir: .
    files:
      - core/core
      - core/utils
      - core/array
      - core/function
      - core/string
      - core/number
      - external/reiterate
      - core/event
      - core/observable
      - core/dom_collection
      - core/dom_insertion
      - core/html_builder
      - core/animation
      - core/region
      - core/sequence
      - core/method_chain
    requires:
      - yui
      - ojay/js-class-min
  pkg/http:
    encode_private_vars: true
    copyright: COPYRIGHT
    source_dir: packages/http
    files:
      - ajax
      - cross_domain
      - uri
    requires:
      - ojay/core-min
  pkg/forms:
    encode_private_vars: true
    copyright: COPYRIGHT
    source_dir: packages/forms
    files:
      - begin
      - utils
      - description
      - requirement
      - data
      - errors
      - dsl
      - inputable
      - checkable
      - radio_buttons
      - checkbox
      - select
      - end
    requires:
      - ojay/core-min
      - ojay/pkg/http-min
  pkg/history:
    encode_private_vars: true
    copyright: COPYRIGHT
    source_dir: packages/history
    files:
      - history
    requires:
      - ojay/core-min
  pkg/keyboard:
    encode_private_vars: true
    copyright: COPYRIGHT
    source_dir: packages/keyboard
    files:
      - begin
      - utils
      - keyboard
      - rules
      - monitor
      - disabler
      - events
      - end
    requires:
      - ojay/core-min
  pkg/mouse:
    encode_private_vars: true
    copyright: COPYRIGHT
    source_dir: packages/mouse
    files:
      - mouse
    requires:
      - ojay/core-min
  pkg/overlay:
    encode_private_vars: true
    copyright: COPYRIGHT
    source_dir: packages/overlay
    files:
      - begin
      - overlay
      - transitions
      - content_overlay
      - tooltip
      - page_mask
      - end
    requires:
      - ojay/core-min
  pkg/paginator:
    encode_private_vars: true
    copyright: COPYRIGHT
    source_dir: packages/paginator
    files:
      - paginator
      - ajax_paginator
      - controls
    requires:
      - ojay/core-min
      - ojay/pkg/http-min
all:
  copyright: COPYRIGHT
  files:
    - js-class
    - core
    - pkg/http
    - pkg/forms
    - pkg/history
    - pkg/keyboard
    - pkg/mouse
    - pkg/overlay
    - pkg/paginator
